### ISSUE TITLE
install with pip

### ISSUE THREAD

**Issue by bgenchel** [oval-group/logger#11]
is there a way to install this library with pip? 

I feel many could be confused between this and the standard python logger library.

**Comment by lberrada** [comment]
Hi, the package is not registered on pypi if that's your question. If needed, you can still use a `pip install -e .` in a local version of the repository (e.g. after a `git clone`).

This is a small and simple package I've found to be useful for my research. It is meant to be a small codebase easy to tweak and adapt, not a large and widespread library. I understand it can be confused for the python `logging` library, but I don't consider this is to be a big issue given the use case. I'm open to suggestions though.

**Comment by bgenchel** [comment]
sure thing; and I apologize for opening an issue about this. There is something that pip can install that is just called 'logger', not 'logging', though I'm now unsure of what that thing is, since PyPI does not have a package that is simply called 'logger'.

**Comment by lberrada** [comment]
No worries. The pypi package seems to be located [here](https://github.com/pavel-paulau/logger/), it's just some configuration for the python standard `logging`.

**Comment by bgenchel** [comment]
If I could make a naive suggestion, not knowing much about use cases and such, perhaps the ambiguity could be resolved by renaming this package 'scientific-logger' or something like that?

But then again, perhaps this ambiguity is so rare it's not worthwhile haha.

**Comment by lberrada** [comment]
Thanks for the suggestion, I'll consider it for future improvements.
