### ISSUE TITLE
Vertical lines in the plots

### ISSUE THREAD

**Issue by prateekpg2455** [oval-group/logger#15]
Is there a way to draw separate vertical dotted lines in any of the plots? It will help me separate out different regimes of the plots. It might not be the only way to do that, in which case, can you suggest how to separate out the same line plot at different indices. I want demarcation line/points to read the different areas correctly. I want something like [this](https://goo.gl/images/vevTCw) where the vertical lines need not be equally spaced. 

I tried this:

```
import numpy as np
for i in np.linspace(0,20,10):
    stats.Loss_Train.update(i).log(100)

```
but it resulted in discotinuation of the line plot. I can think of creating separate tags for each vertical line, but I was thinking if there is an easy way to do this through visdom opts.

**Comment by lberrada** [comment]
Hey Prateek, I'm not aware of an easy way of doing this through visdom opts. That would be more an issue on the visdom side than on the logger one.
